server.port=8080
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://ep-mute-dawn-abryz2av-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
spring.datasource.username=neondb_owner
spring.datasource.password=npg_TuSW2wYcI5QO
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.jwt.secret=classmate-group137-secret-key-knust-2026-very-long-string!!
app.jwt.expiration-ms=86400000

app.cors.allowed-origins=http://localhost:3000,http://localhost:8081,http://10.0.2.2:8080

logging.level.com.knust.classmate=DEBUG
logging.level.org.springframework.security=INFO